/*
Pinot Controller API

Testing SchemaApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/davidgs/golang-api-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_SchemaApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchemaApiService AddSchema1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SchemaApi.AddSchema1(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService DeleteSchema", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var schemaName string

		httpRes, err := apiClient.SchemaApi.DeleteSchema(context.Background(), schemaName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService GetSchema", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var schemaName string

		httpRes, err := apiClient.SchemaApi.GetSchema(context.Background(), schemaName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService GetTableSchema", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tableName string

		httpRes, err := apiClient.SchemaApi.GetTableSchema(context.Background(), tableName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService ListSchemaNames", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SchemaApi.ListSchemaNames(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService UpdateSchema1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var schemaName string

		httpRes, err := apiClient.SchemaApi.UpdateSchema1(context.Background(), schemaName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchemaApiService ValidateSchema1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SchemaApi.ValidateSchema1(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
