/*
Pinot Controller API

Testing AtomicIngestionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/davidgs/golang-api-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_AtomicIngestionApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AtomicIngestionApiService EndDataIngestRequest", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tableName string

		httpRes, err := apiClient.AtomicIngestionApi.EndDataIngestRequest(context.Background(), tableName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AtomicIngestionApiService StartDataIngestRequest", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tableName string

		httpRes, err := apiClient.AtomicIngestionApi.StartDataIngestRequest(context.Background(), tableName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
