/*
Pinot Controller API

APIs for accessing Pinot Controller information

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JobKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobKey{}

// JobKey struct for JobKey
type JobKey struct {
	Name *string `json:"name,omitempty"`
	Group *string `json:"group,omitempty"`
}

// NewJobKey instantiates a new JobKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobKey() *JobKey {
	this := JobKey{}
	return &this
}

// NewJobKeyWithDefaults instantiates a new JobKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobKeyWithDefaults() *JobKey {
	this := JobKey{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *JobKey) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobKey) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *JobKey) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *JobKey) SetName(v string) {
	o.Name = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *JobKey) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobKey) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *JobKey) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *JobKey) SetGroup(v string) {
	o.Group = &v
}

func (o JobKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableJobKey struct {
	value *JobKey
	isSet bool
}

func (v NullableJobKey) Get() *JobKey {
	return v.value
}

func (v *NullableJobKey) Set(val *JobKey) {
	v.value = val
	v.isSet = true
}

func (v NullableJobKey) IsSet() bool {
	return v.isSet
}

func (v *NullableJobKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobKey(val *JobKey) *NullableJobKey {
	return &NullableJobKey{value: val, isSet: true}
}

func (v NullableJobKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


